# flake8:noqa

text = """Donald John Trump (born June 14, 1946) is an American politician, media personality, and businessman who is the 47th president of the United States. A member of the Republican Party, he served as the 45th president from 2017 to 2021.

Born in New York City, Trump graduated from the University of Pennsylvania in 1968 with a bachelor's degree in economics. He became president of his family's real estate business in 1971. After bankruptcies affecting his hotels and casinos in the 1990s and 2000s, he began side ventures. From 2004 to 2015, he hosted the reality television show The Apprentice. A political outsider, Trump won the 2016 presidential election against Democratic nominee Hillary Clinton.

In his first term, Trump imposed a travel ban on citizens from six Muslim-majority countries, expanded the U.S.–Mexico border wall, and implemented a family separation policy. He rolled back environmental and business regulations, signed the Tax Cuts and Jobs Act of 2017, and appointed three Supreme Court justices. In foreign policy, Trump withdrew the U.S. from agreements on climate, trade, and Iran's nuclear program; implemented protectionist tariffs and began a trade war with China; and met with North Korean leader Kim Jong Un without reaching an agreement on denuclearization. In response to the COVID-19 pandemic starting in 2020, he downplayed its severity, contradicted guidance from public health officials, and signed the CARES Act stimulus package. Trump was impeached in 2019 for abuse of power and obstruction of Congress, and in 2021 for incitement of insurrection; the Senate acquitted him in both cases. After his first term, scholars and historians ranked him one of the worst presidents in American history.

Trump is the central figure of Trumpism. Many of his comments and actions have been characterized as racist or misogynistic, and he has made false and misleading statements and promoted conspiracy theories to a degree unprecedented in American politics. He lost the 2020 presidential election to Joe Biden but refused to concede, falsely claiming electoral fraud and attempting to overturn the results, including through his involvement in the January 6 Capitol attack in 2021. Between Trump's presidencies, he faced legal issues including being held liable in civil cases for sexual abuse and defamation, and for financial fraud. In 2024, he was found guilty of falsifying business records, making him the first U.S. president convicted of a felony. After winning the 2024 presidential election against Kamala Harris, Trump was sentenced to a penalty-free discharge, and two other felony indictments against him were dismissed.

Trump began his second term by pardoning around 1,500 January 6 rioters, attempting to reduce the size of the federal workforce, and deporting illegal immigrants. His broad and extensive use of executive orders has drawn dozens of lawsuits challenging their legality.

Early life and education
A black-and-white photograph of Trump as a teenager, smiling, wearing a dark pseudo-military uniform with various badges and a light-colored stripe crossing his right shoulder
Trump at New York Military Academy, 1964
Donald John Trump was born on June 14, 1946, at Jamaica Hospital in the New York City borough of Queens, the fourth child of Fred Trump and Mary Anne MacLeod Trump.[1] He is of German and Scottish descent.[2] He grew up with his older siblings, Maryanne, Fred Jr., and Elizabeth, and his younger brother, Robert, in a mansion in the Jamaica Estates neighborhood of Queens.[3] Fred Trump paid his children each about $20,000 a year, equivalent to $265,000 a year in 2024. Trump was a millionaire at age eight by contemporary standards.[a][4]

Trump attended the private Kew-Forest School through seventh grade. He was a difficult child and showed an early interest in his father's business. His father enrolled him in New York Military Academy, a private boarding school, to complete secondary school.[5] Trump considered a show business career but instead in 1964 enrolled at Fordham University.[6] Two years later, he transferred to the Wharton School of the University of Pennsylvania, graduating in May 1968 with a bachelor of science in economics.[7][8]

He was exempted from the draft during the Vietnam War due to bone spurs in his heels.[9]

Business career
Main article: Business career of Donald Trump
Further information: Business projects of Donald Trump in Russia and Tax returns of Donald Trump
Real estate
Starting in 1968, Trump was employed at his father's real estate company, Trump Management, which owned racially segregated middle-class rental housing in New York City's outer boroughs.[10][11] In 1971, his father made him president of the company and he began using the Trump Organization as an umbrella brand.[12] Roy Cohn was Trump's fixer, lawyer, and mentor for 13 years in the 1970s and 1980s.[13] In 1973, Cohn helped Trump countersue the U.S. government for $100 million (equivalent to $686 million in 2023)[14] over its charges that Trump's properties had racial discriminatory practices. Trump's counterclaims were dismissed, and the government's case was settled with the Trumps signing a consent decree agreeing to desegregate.[15] Before age thirty, Trump showed his propensity for litigation, no matter the outcome and cost; even when he lost, he described the case as a win.[16] Helping Trump projects, Cohn was a consigliere whose Mafia connections controlled construction unions.[17] Cohn introduced political consultant Roger Stone to Trump, who enlisted Stone's services to deal with the federal government.[18] Between 1991 and 2009, he filed for Chapter 11 bankruptcy protection for six of his businesses: the Plaza Hotel in Manhattan, the casinos in Atlantic City, New Jersey, and the Trump Hotels & Casino Resorts company.[19][20]

In 1992, Trump, his siblings Maryanne, Elizabeth, and Robert, and his cousin John W. Walter, each with a 20 percent share, formed All County Building Supply & Maintenance Corp. The company had no offices and is alleged to have been a shell company for paying the vendors providing services and supplies for Trump's rental units, then billing those services and supplies to Trump Management with markups of 20–50 percent and more. The owners shared the proceeds generated by the markups. The increased costs were used to get state approval for increasing the rents of his rent-stabilized units.[21]

Manhattan and Chicago developments

Trump in 1985 with a model of one of his aborted Manhattan development projects[22]
Trump attracted public attention in 1978 with the launch of his family's first Manhattan venture: the renovation of the derelict Commodore Hotel, adjacent to Grand Central Terminal.[23] The financing was facilitated by a $400 million city property tax abatement arranged for him by his father who also, jointly with Hyatt, guaranteed a $70 million bank construction loan.[11][24] The hotel reopened in 1980 as the Grand Hyatt Hotel,[25] and that same year, he obtained rights to develop Trump Tower, a mixed-use skyscraper in Midtown Manhattan.[26] The building houses the headquarters of the Trump Corporation and Trump's PAC and was his primary residence until 2019.[27] In 1988, Trump acquired the Plaza Hotel with a loan from a consortium of 16 banks.[28] The hotel filed for bankruptcy protection in 1992, and a reorganization plan was approved a month later, with the banks taking control of the property.[29]

In 1995, he defaulted on over $3 billion of bank loans, and the lenders seized the Plaza Hotel along with most of his other properties in a "vast and humiliating restructuring" that allowed him to avoid personal bankruptcy.[30][31] The lead bank's attorney said of the banks' decision that they "all agreed that he'd be better alive than dead".[30] In 1996, Trump acquired and renovated the mostly vacant 71-story skyscraper at 40 Wall Street, later rebranded as the Trump Building.[32] In the early 1990s, he won the right to develop a 70-acre (28 ha) tract in the Lincoln Square neighborhood near the Hudson River. Struggling with debt from other ventures in 1994, he sold most of his interest in the project to Asian investors, who financed the project's completion, Riverside South.[33] Trump's last major construction project was the 92-story mixed-use Trump International Hotel and Tower in Chicago which opened in 2008. In 2024, The New York Times and ProPublica reported that the Internal Revenue Service was investigating whether he had twice written off losses incurred through construction cost overruns and lagging sales of residential units in the building he had declared to be worthless on his 2008 tax return.[34]

Atlantic City casinos
The entrance of the Trump Taj Mahal, a casino in Atlantic City. It has motifs evocative of the Taj Mahal in India.
Entrance of the Trump Taj Mahal in Atlantic City
In 1984, Trump opened Harrah's at Trump Plaza, a hotel and casino, with financing and management help from the Holiday Corporation.[35] It was unprofitable, and he paid Holiday $70 million in May 1986 to take sole control.[36] In 1985, he bought the unopened Atlantic City Hilton Hotel and renamed it Trump Castle.[37] Both casinos filed for Chapter 11 bankruptcy protection in 1992.[38] Trump bought a third Atlantic City venue in 1988, the Trump Taj Mahal. It was financed with $675 million in junk bonds and completed for $1.1 billion, opening in April 1990.[35] He filed for Chapter 11 bankruptcy protection in 1991. Under the provisions of the restructuring agreement, he gave up half his initial stake and personally guaranteed future performance.[39] To reduce his $900 million of personal debt, he sold the Trump Shuttle airline; his megayacht, the Trump Princess, which had been leased to his casinos and kept docked; and other businesses.[40] In 1995, Trump founded Trump Hotels & Casino Resorts (THCR), which assumed ownership of the Trump Plaza.[41] THCR purchased the Taj Mahal and the Trump Castle in 1996 and went bankrupt in 2004 and 2009, leaving him with 10 percent ownership.[35] He remained chairman until 2009.[42]

Clubs
In 1985, Trump acquired the Mar-a-Lago estate in Palm Beach, Florida.[43] In 1995, he converted the estate into a private club with an initiation fee and annual dues. He continued to use a wing of the house as a private residence.[44] He declared the club his primary residence in 2019.[27] He began building and buying golf courses in 1999, owning 17 golf courses by 2016.[45]

Licensing the Trump name
See also: List of things named after Donald Trump
The Trump Organization has licensed the Trump name for consumer products and services, including foodstuffs, apparel, learning courses, and home furnishings.[46] According to The Washington Post, there are more than 50 licensing or management deals involving his name, and they have generated at least $59 million for his companies.[47] By 2018, only two consumer goods companies continued to license his name.[46]

Side ventures
Trump, Doug Flutie, and an unnamed official standing behind a lectern with big, round New Jersey Generals sign, with members of the press seated in the background
Trump and New Jersey Generals quarterback Doug Flutie at a 1985 press conference in Trump Tower
In 1970, Trump invested $70,000 to receive billing as coproducer of a Broadway comedy.[48] In September 1983, he purchased the New Jersey Generals, a team in the United States Football League. After the 1985 season, the league folded, largely due to his attempt to move to a fall schedule (when it would have competed with the National Football League [NFL] for audience) and trying to force a merger with the NFL by bringing an antitrust suit.[49] Trump and his Plaza Hotel hosted several boxing matches at the Atlantic City Convention Hall.[35][50] In 1989 and 1990, he lent his name to the Tour de Trump cycling stage race, an attempt to create an American equivalent of European races such as the Tour de France or the Giro d'Italia.[51] From 1986 to 1988, he purchased significant blocks of shares in various public companies while suggesting that he intended to take over the company and then sold his shares for a profit,[52] leading some observers to think he was engaged in greenmail.[53] The New York Times found that he initially made millions of dollars in such stock transactions, but "lost most, if not all, of those gains after investors stopped taking his takeover talk seriously".[52]

A red star with a bronze outline and "Donald Trump" and a TV icon written on it in bronze, embedded in a black terrazzo sidewalk
Trump's star on the Hollywood Walk of Fame
In 1988, Trump purchased the Eastern Air Lines Shuttle, financing the purchase with $380 million (equivalent to $979 million in 2023)[14] in loans from a syndicate of 22 banks. He renamed the airline Trump Shuttle and operated it until 1992.[54] He defaulted on his loans in 1991, and ownership passed to the banks.[55] In 1996, he purchased the Miss Universe pageants, including Miss USA and Miss Teen USA.[56] Due to disagreements with CBS about scheduling, he took both pageants to NBC in 2002.[57][58] In 2007, he received a star on the Hollywood Walk of Fame for his work as producer of Miss Universe.[59] NBC and Univision dropped the pageants in June 2015 in reaction to his comments about Mexican immigrants.[60]

In 2005, Trump cofounded Trump University, a company that sold real estate seminars for up to $35,000. After New York State authorities notified the company that its use of "university" violated state law (as it was not an academic institution), its name was changed to the Trump Entrepreneur Initiative in 2010.[61] In 2013, the State of New York filed a $40 million civil suit against Trump University, alleging that the company made false statements and defrauded consumers. Additionally, two class actions were filed in federal court against Trump and his companies. Internal documents revealed that employees were instructed to use a hard-sell approach, and former employees testified that Trump University had defrauded or lied to its students.[62] Shortly after he won the 2016 presidential election, he agreed to pay a total of $25 million to settle the three cases.[63]

Foundation
Main article: Donald J. Trump Foundation
The Donald J. Trump Foundation was a private foundation established in 1988.[64] From 1987 to 2006, Trump gave his foundation $5.4 million which had been spent by the end of 2006. After donating a total of $65,000 in 2007–2008, he stopped donating any personal funds to the charity,[65] which received millions from other donors, including $5 million from Vince McMahon.[66] The foundation gave to health- and sports-related charities, conservative groups,[67] and charities that held events at Trump properties.[65] In 2016, The Washington Post reported that the charity committed several potential legal and ethical violations, including alleged self-dealing and possible tax evasion.[68] Also in 2016, the New York attorney general determined the foundation to be in violation of state law, for soliciting donations without submitting to required annual external audits, and ordered it to cease its fundraising activities in New York immediately.[69] Trump's team announced in December 2016 that the foundation would be dissolved.[70] In June 2018, the New York attorney general's office filed a civil suit against the foundation, Trump, and his adult children, seeking $2.8 million in restitution and additional penalties.[71] In December 2018, the foundation ceased operation and disbursed its assets to other charities.[72] In November 2019, a New York state judge ordered Trump to pay $2 million to a group of charities for misusing the foundation's funds, in part to finance his presidential campaign.[73]

Legal affairs and bankruptcies
Main article: Personal and business legal affairs of Donald Trump
According to a review of state and federal court files conducted by USA Today in 2018, Trump and his businesses had been involved in more than 4,000 state and federal legal actions.[74] While he has not filed for personal bankruptcy, his over-leveraged hotel and casino businesses in Atlantic City and New York filed for Chapter 11 bankruptcy protection six times between 1991 and 2009.[75] They continued to operate while the banks restructured debt and reduced his shares in the properties.[75] During the 1980s, more than 70 banks had lent Trump $4 billion.[76] After his corporate bankruptcies of the early 1990s, most major banks, with the exception of Deutsche Bank, declined to lend to him.[77] After the January 6 Capitol attack, the bank decided not to do business with him or his company in the future.[78]

Wealth
Main article: Wealth of Donald Trump
Ivana Trump and King Fahd shake hands, with Ronald Reagan standing next to them smiling
Trump (rightmost) and wife Ivana at a 1985 state dinner for King Fahd of Saudi Arabia with President Ronald Reagan and First Lady Nancy Reagan
Trump has often said he began his career with "a small loan of a million dollars" from his father and that he had to pay it back with interest.[79] He borrowed at least $60 million from his father, largely did not repay the loans, and received another $413 million (2018 equivalent, adjusted for inflation) from his father's company.[80][21] Posing as a Trump Organization official named "John Barron", Trump called journalist Jonathan Greenberg in 1984, trying to get a higher ranking on the Forbes 400 list of wealthy Americans.[81] Trump self-reported his net worth over a wide range: from a low of minus $900 million in 1990,[b] to a high of $10 billion in 2015.[84] In 2024, Forbes estimated his net worth at $2.3 billion and ranked him the 1,438th wealthiest person in the world.[85]

Media career
Main article: Media career of Donald Trump
See also: Bibliography of Donald Trump
Trump has produced 19 books under his name, most written or cowritten by ghostwriters.[86] His first book, The Art of the Deal (1987), was a New York Times Best Seller, and was credited by The New Yorker with making Trump famous as an "emblem of the successful tycoon".[87] The book was ghostwritten by Tony Schwartz, who is credited as a coauthor. Trump had cameos in many films and television shows from 1985 to 2001.[88] Starting in the 1990s, Trump was a guest 24 times on the nationally syndicated Howard Stern Show.[89] He had his own short-form talk radio program, Trumped!, from 2004 to 2008.[90] From 2011 until 2015, he was a guest commentator on Fox & Friends.[91] In 2021, Trump, who had been a member since 1989, resigned from SAG-AFTRA to avoid a disciplinary hearing regarding the January 6 attack.[92] Two days later, the union permanently barred him.[93]

The Apprentice and The Celebrity Apprentice
Main articles: The Apprentice and The Celebrity Apprentice
Producer Mark Burnett made Trump a television star[94] when he created The Apprentice, which Trump hosted from 2004 to 2015 (including variant The Celebrity Apprentice). On the shows, he was a superrich chief executive who eliminated contestants with the catchphrase "you're fired". The New York Times called his portrayal "a highly flattering, highly fictionalized version" of himself.[95] The shows remade Trump's image for millions of viewers nationwide.[95][96] With the related licensing agreements, they earned him more than $400 million.[97]

Early political aspirations
Further information: Political career of Donald Trump
Trump registered as a Republican in 1987;[98] a member of the Independence Party, the New York state affiliate of the Reform Party, in 1999;[99] a Democrat in 2001; a Republican in 2009; unaffiliated in 2011; and a Republican in 2012.[98]

Trump, leaning heavily onto a lectern, with his mouth open mid-speech and a woman clapping politely next to him
Trump speaking at CPAC 2011
In 1987, Trump placed full-page advertisements in three major newspapers,[100] expressing his views on foreign policy and how to eliminate the federal budget deficit.[101] In 1988, he approached Lee Atwater, asking to be put into consideration to be Republican nominee George H. W. Bush's running mate. Bush found the request "strange and unbelievable".[102][103] Trump was a candidate in the 2000 Reform Party presidential primaries for three months, but withdrew from the race in February 2000.[104][105][106] In 2011, Trump speculated about running against President Barack Obama in the 2012 election, making his first speaking appearance at the Conservative Political Action Conference in February and giving speeches in early primary states.[107][108] In May 2011, he announced he would not run.[107]

2016 presidential election
Main article: Donald Trump 2016 presidential campaign
Further information: 2016 Republican Party presidential primaries, 2016 United States presidential election, and First presidential transition of Donald Trump
Trump announced his candidacy in June 2015.[109][110] He became the Republican front-runner in March 2016[111] and was declared the presumptive Republican nominee in May.[112] His campaign statements were often opaque and suggestive,[113] and a record number were false.[114][115][116] He was highly critical of media coverage and frequently made claims of media bias.[117][118] Hillary Clinton led Trump in national polling averages throughout the campaign, but, in early July, her lead narrowed.[119] In mid-July, he selected Indiana governor Mike Pence as his running mate,[120] and the two were officially nominated at the 2016 Republican National Convention.[121] Trump and Clinton faced off in three presidential debates in September and October 2016. He twice refused to say whether he would accept the result of the election.[122]

Trump speaking in front of an American flag behind a lectern, wearing a black suit and red hat. The lectern sports a blue "TRUMP" sign.
Trump campaigning in Arizona, March 2016
Trump described NATO as "obsolete"[123][124] and espoused views that were described as noninterventionist and protectionist.[125] His campaign platform emphasized renegotiating U.S.–China relations and free trade agreements such as NAFTA and strongly enforcing immigration laws. Other campaign positions included pursuing energy independence while opposing climate change regulations, modernizing services for veterans, repealing and replacing the Affordable Care Act, abolishing Common Core education standards, investing in infrastructure, simplifying the tax code while reducing taxes, and imposing tariffs on imports by companies that offshore jobs. He advocated increasing military spending and extreme vetting or banning of immigrants from Muslim-majority countries.[126] Trump's proposed immigration policies were a topic of bitter debate during the 2016 campaign. He promised to build a wall on the Mexico–U.S. border to restrict illegal movement and vowed that Mexico would pay for it.[127] He pledged to deport millions of illegal immigrants residing in the U.S.,[128] and criticized birthright citizenship for incentivizing "anchor babies".[129] According to an analysis in Political Science Quarterly, Trump made "explicitly racist appeals to whites" during his 2016 presidential campaign.[130] In particular, his campaign launch speech drew criticism for claiming Mexican immigrants were "bringing drugs, they're bringing crime, they're rapists";[131] in response, NBC fired him from Celebrity Apprentice.[132]

Trump's FEC-required reports listed assets above $1.4 billion and outstanding debts of at least $315 million.[133][134] He did not release his tax returns, contrary to the practice of every major candidate since 1976 and his promises in 2014 and 2015 to do so if he ran for office.[135][136] He said his tax returns were being audited, and that his lawyers had advised him against releasing them.[137] After a lengthy court battle to block release of his tax returns and other records to the Manhattan district attorney for a criminal investigation, including two appeals by Trump to the U.S. Supreme Court, in February 2021 the high court allowed the records to be released to the prosecutor for review by a grand jury.[138][139] In October 2016, portions of Trump's state filings for 1995 were leaked to a reporter from The New York Times. They show that he had declared a loss of $916 million that year, which could have let him avoid taxes for up to 18 years.[140]

On November 8, 2016, Trump received 306 pledged electoral votes versus 232 for Clinton. After elector defections on both sides, the official count was 304 to 227.[141] The fifth person to be elected president while losing the popular vote,[c] he received nearly 2.9 million fewer votes than Clinton, 46.3% to her 48.25%.[142] He was the only president who neither served in the military nor held any government office prior to becoming president.[143] Trump won 30 states, including Michigan, Pennsylvania, and Wisconsin, states which had been considered a blue wall of Democratic strongholds since the 1990s. His victory marked the return of an undivided Republican government—a Republican president combined with Republican control of both chambers of Congress.[144] Trump's victory sparked protests in major U.S. cities.[145][146]

First presidency (2017–2021)
Main article: First presidency of Donald Trump
For a chronological guide, see Timeline of the Donald Trump presidencies.
Early actions
See also: First presidential transition of Donald Trump and First 100 days of the first Donald Trump presidency
Trump, with his family watching, raises his right hand and places his left hand on the Bible as he takes the oath of office. Roberts stands opposite him administering the oath
Trump took his first oath of office, administered by Chief Justice John G. Roberts Jr., at the Capitol on January 20, 2017.
A head-and-shoulders portrait of Trump beaming in front of the U.S. flag, wearing a dark blue suit jacket with American flag lapel pin, white shirt, and light blue necktie.
Official portrait, 2017
Trump was inaugurated on January 20, 2017. The day after his inauguration, an estimated 2.6 million people worldwide, including a half million in Washington, D.C., protested against him in the Women's Marches.[147] During his first week in office, Trump signed six executive orders, including authorizing procedures for repealing the Patient Protection and Affordable Care Act ("Obamacare"), withdrawal from the Trans-Pacific Partnership negotiations, advancement of the Keystone XL and Dakota Access Pipeline projects, and planning for a wall along the U.S. border with Mexico.[148]

Conflicts of interest
See also: First presidency of Donald Trump § Ethics
Before being inaugurated, Trump moved his businesses into a revocable trust,[149][150] rather than a blind trust or equivalent arrangement "to cleanly sever himself from his business interests".[151] He continued to profit from his businesses and knew how his administration's policies affected them.[150][152] Although he said he would eschew "new foreign deals", the Trump Organization pursued operational expansions in Scotland, Dubai, and the Dominican Republic.[150][152] Lobbyists, foreign government officials, and Trump donors and allies generated hundreds of millions of dollars for his resorts and hotels.[153] Trump was sued for violating the Domestic and Foreign Emoluments Clauses of the U.S. Constitution, the first time that the clauses had been substantively litigated.[154] One case was dismissed in lower court.[155] Two were dismissed by the U.S. Supreme Court as moot after his term.[156]

Domestic policy
Main articles: Economic policy of the first Donald Trump administration, Environmental policy of the first Donald Trump administration, and Social policy of the first Donald Trump administration
Trump took office at the height of the longest economic expansion in American history,[157] which began in 2009 and continued until February 2020, when the COVID-19 recession began.[158] In December 2017, he signed the Tax Cuts and Jobs Act of 2017. It reduced tax rates for businesses and individuals and set the penalty associated with the Affordable Care Act's individual mandate to $0.[159][160] The Trump administration claimed that the act would not decrease government revenue, but 2018 revenues were 7.6 percent lower than projected.[161] Under Trump, the federal budget deficit increased by almost 50 percent, to nearly $1 trillion in 2019.[162] By the end of his term, the U.S. national debt increased by 39 percent, reaching $27.75 trillion, and the U.S. debt-to-GDP ratio hit a post-World War II high.[163] Trump also failed to deliver the $1 trillion infrastructure spending plan on which he had campaigned.[164]

Trump is the only modern U.S. president to leave office with a smaller workforce than when he took office, by three million people.[157][165] Trump rejects the scientific consensus on climate change.[166][167][168][169] He reduced the budget for renewable energy research by 40 percent and reversed Obama-era policies directed at curbing climate change.[170] He withdrew from the Paris Agreement, making the U.S. the only nation to not ratify it.[171] He aimed to boost the production and exports of fossil fuels.[172][173] Natural gas expanded under Trump, but coal continued to decline.[174][175] He rolled back more than 100 federal environmental regulations, including those that curbed greenhouse gas emissions, air and water pollution, and the use of toxic substances. He weakened protections for animals and environmental standards for federal infrastructure projects, and expanded permitted areas for drilling and resource extraction, such as allowing drilling in the Arctic Refuge.[176]

Trump dismantled many federal regulations on health,[177][178] labor,[178] and the environment,[179][178] among others, including a bill that made it easier for severely mentally ill persons to buy guns.[180] During his first six weeks in office, he delayed, suspended, or reversed ninety federal regulations,[181] often "after requests by the regulated industries".[182] The Institute for Policy Integrity found that 78 percent of his proposals were blocked by courts or did not prevail over litigation.[183] During his campaign, Trump vowed to repeal and replace the Affordable Care Act.[184] In office, he scaled back the Act's implementation through executive orders.[185][186] He expressed a desire to "let Obamacare fail"; his administration halved the enrollment period and drastically reduced funding for enrollment promotion.[187][188] In June 2018, the Trump administration joined 18 Republican-led states in arguing before the Supreme Court that the elimination of the financial penalties associated with the individual mandate had rendered the Act unconstitutional.[189][190] Their pleading would have eliminated health insurance coverage for up to 23 million Americans, but was unsuccessful.[189] During the 2016 campaign, Trump promised to protect funding for Medicare and other social safety-net programs. In January 2020, he expressed willingness to consider cuts to them.[191]

In response to the opioid epidemic, Trump signed legislation in 2018 to increase funding for drug treatments, but was widely criticized for failing to make a concrete strategy.[192] He barred organizations that provide abortions or abortion referrals from receiving federal funds.[193] He said he supported "traditional marriage", but considered the nationwide legality of same-sex marriage "settled".[194] His administration rolled back key components of the Obama administration's workplace protections against discrimination of LGBTQ people.[195] His attempted rollback of anti-discrimination protections for transgender patients in August 2020 was halted by a federal judge after a Supreme Court ruling extended employees' civil rights protections to gender identity and sexual orientation.[196] Trump has said he is opposed to gun control, although his views have shifted over time.[197] His administration took an anti-marijuana position, revoking Obama-era policies that provided protections for states that legalized marijuana.[198] He is a long-time advocate of capital punishment,[199][200] and his administration oversaw the federal government execute 13 prisoners, more than in the previous 56 years combined, ending a 17-year moratorium.[201] In 2016, he said he supported the use of interrogation torture methods such as waterboarding.[202][203]

Race relations
Trump's comments on the 2017 Unite the Right rally, condemning "this egregious display of hatred, bigotry and violence on many sides" and stating that there were "very fine people on both sides", were criticized as implying a moral equivalence between the white supremacist demonstrators and the counter-protesters.[204] In a January 2018 discussion of immigration legislation, he reportedly referred to El Salvador, Haiti, Honduras, and African nations as "shithole countries".[205] His remarks were condemned as racist.[206]


Trump and group of officials and advisors on the way from the White House to St. John's Church
In July 2019, Trump tweeted that four Democratic congresswomen—all minorities, three of whom are native-born Americans—should "go back" to the countries they "came from".[207] Two days later the House of Representatives voted 240–187, mostly along party lines, to condemn his "racist comments".[208] White nationalist publications and social media praised his remarks, which continued over the following days.[209] He continued to make similar remarks during his 2020 campaign.[210] In June 2020, during the George Floyd protests, federal law-enforcement officials controversially removed a largely peaceful crowd of lawful protesters from Lafayette Square, outside the White House.[211][212] Trump then posed with a Bible for a photo-op at the nearby St. John's Episcopal Church,[211][213][214] with religious leaders condemning both the treatment of protesters and the photo opportunity itself.[215] Many retired military leaders and defense officials condemned his proposal to use the U.S. military against anti-police-brutality protesters.[216]

Pardons and commutations
Further information: List of people granted executive clemency by Donald Trump
Trump granted 237 requests for clemency, fewer than all presidents since 1900 with the exception of George H. W. Bush and George W. Bush.[217] Only 25 of them had been vetted by the Justice Department's Office of the Pardon Attorney; the others were granted to people with personal or political connections to him, his family, and his allies, or recommended by celebrities.[218][219] In his last full day in office, he granted 73 pardons and commuted 70 sentences.[220] Several Trump allies were not eligible for pardons under Justice Department rules, and in other cases the department had opposed clemency.[218] The pardons of three military service members convicted of or charged with violent crimes were opposed by military leaders.[221]

Immigration
Main articles: Immigration policy of the first Donald Trump administration and Mexico–United States border crisis § First Trump administration (2017–2021)
Further information: Trump travel ban, Trump administration family separation policy, and Mexico–United States border wall § First Trump administration (2017–2021)
Trump is speaking with U.S. Border Patrol agents. Behind him are black SUVs, four short border wall prototype designs, and the current border wall in the background.
Trump examines border wall prototypes in Otay Mesa, California.
As president, Trump described illegal immigration as an "invasion" of the United States[222] and drastically escalated immigration enforcement.[223][224] He implemented harsh policies against asylum seekers[224] and deployed nearly 6,000 troops the U.S.–Mexico border to stop illegal crossings.[225] He reduced the number of refugees admitted to record lows, from an annual limit of 110,000 before he took office to 15,000 in 2021.[226][227][228] Trump also increased restrictions on granting permanent residency to immigrants needing public benefits.[229] One of his central campaign promises was to build a wall along the U.S.–Mexico border;[230] during his first term, the U.S. built 73 miles (117 km) of wall in areas without barriers and 365 miles (587 km) to replace older barriers.[231] In 2018, Trump's refusal to sign any congressional spending bill unless it allocated funding for the border wall[232] resulted in the longest-ever federal government shutdown, for 35 days from December 2018 to January 2019.[233][234] The shutdown ended after he agreed to fund the government without any funds for the wall.[233] To avoid another shutdown, Congress passed a funding bill with $1.4 billion for border fencing in February.[235] Trump later declared a national emergency on the southern border to divert $6.1 billion of funding to the border wall[235] despite congressional disagreement.[236]

In January 2017, Trump signed an executive order that temporarily denied entry to citizens of seven Muslim-majority countries.[237][238] The order caused many protests and legal challenges that resulted in nationwide injunctions.[237][238][239] A revised order giving some exceptions was also blocked by courts,[240][241] but the Supreme Court ruled in June that the ban could be enforced on those lacking "a bona fide relationship with a person or entity" in the U.S.[242] Trump replaced the ban in September with a presidential proclamation extending travel bans to North Koreans, Chadians, and some Venezuelan officials, but excluded Iraq and Sudan.[243] The Supreme Court allowed that version to go into effect in December 2017,[244] and ultimately upheld the ban in 2019.[245] From 2017 to 2018, the Trump administration had a policy of family separation that separated over 4,400 children of migrant families from their parents at the U.S.–Mexico border,[246][247] an unprecedented[248] policy sparked public outrage in the country.[249] Despite Trump initially blaming Democrats[250][251] and insisting he could not stop the policy with an executive order, he acceded to public pressure in June 2018 and mandated that migrant families be detained together unless "there is a concern" of risk for the child.[252][253] A judge later ordered that the families be reunited and further separations stopped except in limited circumstances,[254][255] though over 1,000 additional children were separated from their families after the order.[247]

Foreign policy
Main articles: Foreign policy of the first Donald Trump administration and First Trump tariffs
Further information: Russia–United States relations § First Trump administration (2017–2021), China–United States relations § First Trump administration (2017–2021), 2017–2018 North Korea crisis, and 2018–19 Korean peace process
See also: List of international presidential trips made by Donald Trump § First presidency (2017–2021)
Trump and other G7 leaders sit at a conference table
Trump with the other G7 leaders at the 45th summit in France, 2019
Trump described himself as a "nationalist"[256] and his foreign policy as "America First".[257] He supported populist, neo-nationalist, and authoritarian governments.[258] Unpredictability, uncertainty, and inconsistency characterized foreign relations during his tenure.[257][259] Tensions between the U.S. and its European allies were strained under Trump.[260] He criticized NATO allies and privately suggested that the U.S. should withdraw from NATO.[261][262] Trump supported many of the policies of Israeli Prime Minister Benjamin Netanyahu.[263] In 2020, the White House hosted the signing of the Abraham Accords between Israel and the United Arab Emirates and Bahrain to normalize their foreign relations.[264]

An economic conflict between China and the United States has been ongoing since January 2018, when Trump began setting tariffs and other trade barriers on China with the goal of forcing it to make changes to what the U.S. says are long-standing unfair trade practices and intellectual property theft.[265] The first Trump administration stated that these practices may contribute to the U.S.–China trade deficit, and that the Chinese government requires transfer of American technology to China.[266] The Trump administration weakened the toughest sanctions imposed by the U.S. after Russia's 2014 annexation of Crimea.[267][268] Trump withdrew the U.S. from the Intermediate-Range Nuclear Forces Treaty, citing alleged Russian noncompliance,[269] and supported a potential return of Russia to the G7.[270] He repeatedly praised and, according to some critics, rarely criticized Russian president Vladimir Putin[271][272] but opposed some actions of the Russian government.[273][274] In 2017, when North Korea's nuclear weapons were increasingly seen as a serious threat,[275] Trump, the first sitting U.S. president to meet a North Korean leader, met Kim three times: in Singapore in June 2018, in Hanoi in February 2019, and in the Korean Demilitarized Zone in June 2019.[276] However, no denuclearization agreement was reached,[277] and talks in October 2019 broke down after one day.[278]

Personnel
Main articles: Political appointments of the first Trump administration and First cabinet of Donald Trump
Trump made daughter Ivanka and son-in-law Jared Kushner unpaid advisors.[279]

The Trump administration had a high turnover of personnel, particularly among White House staff. By the end of his first year in office, 34 percent of his original staff had resigned, been fired, or been reassigned.[280] As of early July 2018, 61 percent of his senior aides had left[281] and 141 staffers had left in the previous year.[282] Both figures set a record for recent presidents.[283] Notable early departures included National Security Advisor Michael Flynn (after just 25 days), and Press Secretary Sean Spicer.[283] Close personal aides to Trump including Steve Bannon, Hope Hicks, John McEntee, and Keith Schiller quit or were forced out.[284] Some later returned in different posts.[285] He publicly disparaged several of his former top officials.[286]

Trump had four White House chiefs of staff, marginalizing or pushing out several.[287] Reince Priebus was replaced after seven months by John F. Kelly.[288] Kelly resigned in December 2018 after a tumultuous tenure in which his influence waned, and Trump subsequently disparaged him.[289] Kelly was succeeded by Mick Mulvaney as acting chief of staff; he was replaced in March 2020 by Mark Meadows.[287] In May 2017, Trump dismissed FBI director James Comey. While initially attributing this action to Comey's conduct in the investigation about Hillary Clinton's emails, Trump said a few days later that he was concerned with Comey's role in the ongoing Trump-Russia investigations.[290] At a private conversation in February, he said he hoped Comey would drop the investigation into Flynn.[291] In March and April, he asked Comey to "lift the cloud impairing his ability to act" by saying publicly that the FBI was not investigating him.[291][292]

Trump lost three of his 15 original cabinet members within his first year.[293] Health and Human Services secretary Tom Price was forced to resign in September 2017 due to excessive use of private charter jets and military aircraft.[293][284] Environmental Protection Agency administrator Scott Pruitt resigned in 2018 and Secretary of the Interior Ryan Zinke in January 2019 amid multiple investigations into their conduct.[294][295] Trump was slow to appoint second-tier officials in the executive branch, saying many of the positions are unnecessary. In October 2017, there were hundreds of sub-cabinet positions without a nominee.[296] By January 8, 2019, of 706 key positions, 433 had been filled and he had no nominee for 264.[297]

Judiciary
Further information: List of federal judges appointed by Donald Trump and Donald Trump judicial appointment controversies
Trump appointed 226 Article III judges, including 54 to the courts of appeals and three to the Supreme Court: Neil Gorsuch, Brett Kavanaugh, and Amy Coney Barrett.[298] His Supreme Court nominees were noted as having politically shifted the Court to the right.[299][300][301] In the 2016 campaign, he pledged that Roe v. Wade would be overturned "automatically" if he were elected and provided the opportunity to appoint two or three anti-abortion justices. He later took credit when Roe was overturned in Dobbs v. Jackson Women's Health Organization; all three of his Supreme Court nominees voted with the majority.[302][303] Trump disparaged courts and judges he disagreed with, often in personal terms, and questioned the judiciary's constitutional authority. His attacks on the courts drew rebukes from observers, including sitting federal judges, concerned about the effect of his statements on the judicial independence and public confidence in the judiciary.[304][305]

COVID-19 pandemic
Main article: COVID-19 pandemic in the United States
Further information: U.S. federal government response to the COVID-19 pandemic and Communication of the Trump administration during the COVID-19 pandemic
See also: Economic impact of the COVID-19 pandemic in the United States
Trump speaks in the West Wing briefing room with various officials standing behind him, all in formal attire and without face masks
Trump conducts a COVID-19 press briefing with members of the White House Coronavirus Task Force on March 15, 2020.
Trump initially ignored public health warnings and calls for action from health officials within his administration and Azar,[306] focusing on economic and political considerations of the outbreak.[307] Trump established the White House Coronavirus Task Force on January 29.[308] Prior to the pandemic, Trump criticized the WHO and other international bodies, which he asserted were taking advantage of U.S. aid.[309] On March 27, he signed into law the CARES Act—a $2.2 trillion economic stimulus bill—the largest stimulus in U.S. history.[310][311] In April 2020, Republican-connected groups organized anti-lockdown protests against the measures state governments were taking to combat the pandemic;[312][313] Trump encouraged the protests on Twitter,[314] although the targeted states did not meet his administration's guidelines for reopening.[315] He repeatedly pressured federal health agencies to take actions he favored,[316] such as approving unproven treatments.[317][318] On October 2, 2020, he tweeted that he had tested positive for COVID-19, part of a White House outbreak.[319] By July 2020, Trump's handling of the COVID-19 pandemic had become a major issue in the presidential election.[320]

Investigations
Further information: Russian interference in the 2016 United States elections, Mueller special counsel investigation, and Mueller report
After he assumed office, Trump was the subject of increasing Justice Department and congressional scrutiny, with investigations covering his election campaign, transition, and inauguration, actions taken during his presidency, his private businesses, personal taxes, and charitable foundation.[321] There were ten federal criminal investigations, eight state and local investigations, and twelve congressional investigations.[322]

In July 2016, the FBI launched Crossfire Hurricane, an investigation into possible links between Russia and Trump's 2016 campaign.[323] After Trump fired Comey in May 2017, the FBI opened a second investigation into Trump's personal and business dealings with Russia.[324] In January 2017, three U.S. intelligence agencies jointly stated with "high confidence" that Russia interfered in the 2016 presidential election to favor Trump.[325][326] Many suspicious[327] links between Trump associates and Russian officials were discovered.[328][329][330] Trump told Russian officials he was unconcerned about Russia's election interference.[331] Crossfire Hurricane was later transferred to Robert Mueller's special counsel investigation;[332] the investigation into Trump's ties to Russia was ended by Deputy Attorney General Rod Rosenstein after he told the FBI that Mueller would pursue the matter.[333][334] At the request of Rosenstein, the Mueller investigation examined criminal matters "in connection with Russia's 2016 election interference".[333] Mueller submitted his final report in March 2019.[335] The report found that Russia did interfere in 2016 to favor Trump[336] and that Trump and his campaign welcomed and encouraged the effort,[337][338][339] but that the evidence "did not establish" that Trump campaign members conspired or coordinated with Russia.[340][341] Trump claimed the report exonerated him despite Mueller writing that it did not.[342] The report also detailed potential obstruction of justice by Trump but "did not draw ultimate conclusions"[343][344] and left the decision to charge the laws to Congress.[345]

In April 2019, the House Oversight Committee issued subpoenas seeking financial details from Trump's banks, Deutsche Bank and Capital One, and his accounting firm, Mazars USA. He sued the banks, Mazars, and committee chair Elijah Cummings to prevent the disclosures.[346] In May, two judges ruled that both Mazars and the banks must comply with the subpoenas;[347][348][349] Trump's attorneys appealed.[350] In September 2022, Trump and the committee agreed to a settlement regarding Mazars, and the firm began turning over documents.[351]

Impeachments
Main articles: First impeachment of Donald Trump and Second impeachment of Donald Trump

Trump displaying the headline "Trump acquitted"
Trump was impeached twice by the House of Representatives during his first presidential term. On each occasion, he was acquitted by the Senate. The first impeachment arose from a whistleblower complaint that in 2019 Trump had pressured Ukrainian president Volodymyr Zelenskyy to investigate Joe and Hunter Biden,[352] in an attempt to gain an advantage in the 2020 presidential election.[353] On December 18, 2019, the House voted to impeach Trump for abuse of power and obstruction of Congress,[354] and the Senate acquitted him on February 5, 2020.[355] The second impeachment came after the Capitol riot, over which the House charged Trump with incitement of insurrection on January 13, 2021.[356] Trump left office on January 20, and the Senate acquitted him on February 13.[357]

2020 presidential election
Further information: 2020 United States presidential election
Presidential campaign
Main article: Donald Trump 2020 presidential campaign
Trump filed to run for reelection only a few hours after becoming president in 2017.[358] He held his first reelection rally less than a month after taking office[359] and officially became the Republican nominee in August 2020.[360] Trump's campaign focused on crime, claiming that cities would descend into lawlessness if Democratic nominee Joe Biden won.[361] He repeatedly misrepresented Biden's positions[362][363] and appealed to racism.[364] Starting in early 2020, Trump sowed doubts about the election, claiming without evidence that it would be rigged and that widespread use of mail balloting would produce massive election fraud.[365][366] He blocked funding for the U.S. Postal Service, saying he wanted to prevent any increase in voting by mail.[367] He repeatedly refused to say whether he would accept the results if he lost and commit to a peaceful transition of power.[368][369]

Loss to Biden and rejection of results
Further information: Attempts to overturn the 2020 United States presidential election and 2020–21 United States election protests
Biden won the November 2020 election, receiving 81.3 million votes (51.3 percent) to Trump's 74.2 million (46.8 percent)[370][371] and 306 electoral votes to Trump's 232.[372] The Electoral College formalized Biden's victory on December 14.[372]

Even before the results were known on the morning after the election, Trump declared victory.[373] Days later, when Biden was projected the winner, Trump baselessly alleged election fraud.[374] As part of an effort to overturn the results, Trump and his allies filed many legal challenges to the results, which were rejected by at least 86 judges in both state and federal courts for having no factual or legal basis.[375][376]

Trump's allegations were also refuted by state election officials,[377] and the Supreme Court declined to hear a case asking it to overturn the results in four states won by Biden.[378] Trump repeatedly sought help to overturn the results, personally pressuring Republican local and state office-holders,[379] Republican legislators,[380] the Justice Department,[381] and Vice President Pence,[382] urging various actions such as replacing presidential electors, or requesting that Georgia officials "find" votes and announce a "recalculated" result.[380]

In the weeks after the election, Trump withdrew from public activities.[383] He initially blocked government officials from cooperating in Biden's presidential transition.[384][385] After three weeks, the administrator of the General Services Administration declared Biden the "apparent winner" of the election, allowing the disbursement of transition resources to his team.[386] While Trump said he recommended that the GSA begin transition protocols, he still did not formally concede.[387][388] Trump did not attend Biden's inauguration on January 20.[389]

January 6 Capitol attack
Main article: January 6 United States Capitol attack

A crowd of Trump supporters during the January 6 attack on the U.S. Capitol in 2021
In December 2020, reports emerged that the U.S. military was on "red alert", and ranking officers had discussed what to do if Trump declared martial law.[390] Joint Chiefs of Staff chairman Mark Milley and CIA director Gina Haspel grew concerned that Trump would attempt a coup or military action against China or Iran.[391][392] Milley insisted that he be consulted about any military orders from Trump, including the use of nuclear weapons.[393][394]

At noon on January 6, 2021, while Congress was certifying the presidential election results at the U.S. Capitol, Trump held a rally at the Ellipse in Washington, D.C., where he called for the election to be overturned and urged his supporters to "fight like hell" and "take back our country" by marching to the Capitol.[395] His supporters then formed a mob that broke into the building, disrupting certification and causing the evacuation of Congress.[396] During the attack, Trump posted on social media but did not ask the rioters to disperse until 6 p.m., when he told them in a tweet to "go home with love & in peace" while calling them "great patriots" and restating that he had won the election.[397] Congress later reconvened and confirmed Biden's victory in the early hours of January 7.[398] More than 140 police officers were injured, and five people died either during or after the attack.[399][400] The event has been described as an attempted self-coup by Trump.[d]

Between terms (2021–2025)
Main articles: Georgia election racketeering prosecution, Federal prosecution of Donald Trump (election obstruction case), Federal prosecution of Donald Trump (classified documents case), Prosecution of Donald Trump in New York, and E. Jean Carroll v. Donald J. Trump
See also: Personal and business legal affairs of Donald Trump and Legal affairs of Donald Trump as president
Upon leaving the White House, Trump began living at Mar-a-Lago, establishing an office there as provided for by the Former Presidents Act.[404] His continuing false claims concerning the 2020 election were commonly referred to as the "big lie" by his critics, although in May 2021, with his supporters he began using the term to refer to the election itself.[405][406] The Republican Party used his election narrative to justify imposing new voting restrictions in its favor.[407][408][409] As of July 2022, he continued to pressure state legislators to overturn the election.[410] Unlike other former presidents, Trump continued to dominate his party; a 2022 profile in The New York Times described him as a modern party boss.[411] He continued fundraising, raising a war chest containing more than twice that of the Republican Party, and profited from fundraisers many Republican candidates held at Mar-a-Lago. Much of his focus was on party governance and installing in key posts officials loyal to him.[411] In the 2022 midterm elections, he endorsed over 200 candidates for various offices.[412] In February 2021, he registered a new company, Trump Media & Technology Group (TMTG), for providing "social networking services" to U.S. customers.[413][414] In March 2024, TMTG merged with special-purpose acquisition company Digital World Acquisition and became a public company.[415] In February 2022, TMTG launched Truth Social, a social media platform.[416]

In 2019, journalist E. Jean Carroll accused Trump of raping her in the 1990s and sued him for defamation over his denial.[417] Carroll sued him again in 2022 for battery and more defamation.[418] He was found liable for sexual abuse and defamation and ordered to pay $5 million in one case[419] and $83.3 million in the other.[419][420] In 2022, New York filed a civil lawsuit was filed against Trump accusing him of inflating The Trump Organization's value to gain an advantage with lenders and banks;[421][422] He was found liable and ordered to pay $350 million plus interest.[422]


Classified intelligence material found during search of Mar-a-Lago
In connection with Trump's efforts to overturn the 2020 election and his involvement in the January 6 attack, in December 2022 the U.S. House committee on the attack recommended criminal charges against him for obstructing an official proceeding, conspiracy to defraud the United States, and inciting or assisting an insurrection.[423] In August 2023, he was indicted on 13 charges, including racketeering, by a grand jury in Fulton County, Georgia for his efforts to subvert the 2020 election in the state.[424][425]

In January 2022, the National Archives and Records Administration retrieved 15 boxes of documents Trump had taken to Mar-a-Lago after leaving the White House, some of which were classified.[426] In the ensuing Justice Department investigation, officials retrieved more classified documents from his lawyers.[426] On August 8, 2022, FBI agents searched Mar-a-Lago for illegally held documents, including those in breach of the Espionage Act, collecting 11 sets of classified documents, some marked top secret.[427][428] A federal grand jury constituted by Special Counsel Jack Smith indicted Trump in June 2023 on 31 counts of "willfully retaining national defense information" under the Espionage Act, among other charges.[426][429][430] Trump pleaded not guilty.[431] In July 2024, judge Aileen Cannon dismissed the case, ruling Smith's appointment as special prosecutor was unconstitutional.[432]

In May 2024, Trump was convicted on 34 felony counts of falsifying business records.[433] The case stemmed from evidence that he booked Michael Cohen's hush-money payments to adult film actress Stormy Daniels as business expenses to cover up his alleged 2006–2007 affair with Daniels during the 2016 election.[433][434] On January 10, 2025, the judge gave Trump a no-penalty sentence known as an unconditional discharge, saying that punitive requirements would have interfered with presidential immunity.[435] After his reelection, the 2020 election obstruction case and the classified documents case were dismissed without prejudice due to Justice Department policy against prosecuting sitting presidents.[436]

2024 presidential election
Main article: Donald Trump 2024 presidential campaign
Further information: 2024 Republican Party presidential primaries, 2024 United States presidential election, and Second presidential transition of Donald Trump

Trump at a rally in Arizona, August 2024
On November 15, 2022, Trump announced his candidacy for the 2024 presidential election and set up a fundraising account.[437][438] In March 2023, the campaign began diverting 10 percent of the donations to his leadership PAC. His campaign had paid $100 million towards his legal bills by March 2024.[439][440] In December 2023, the Colorado Supreme Court ruled him disqualified for the Colorado Republican primary for his role in inciting the January 6, 2021, attack on Congress. In March 2024, the U.S. Supreme Court restored his name to the ballot in a unanimous decision, ruling that Colorado lacks the authority to enforce Section 3 of the 14th Amendment, which bars insurrectionists from holding federal office.[441]

During the campaign, Trump made increasingly violent and authoritarian statements.[442][443][444][445] He also said that he would weaponize the FBI and the Justice Department against his political opponents[446][447] and use the military to go after Democratic politicians and those that do not support his candidacy.[448][449] He used harsher, more dehumanizing anti-immigrant rhetoric than during his presidency.[450][451][452][453] His harsher rhetoric against his political enemies has been described by some historians and scholars as authoritarian, fascist,[e] and unlike anything a political candidate has ever said in American history.[458][449][459] Age and health concerns also arose during the campaign, with several medical experts highlighting an increase in rambling, tangential speech and behavioral disinhibition.[460]

Trump mentioned "rigged election" and "election interference" earlier and more frequently than in the 2016 and 2020 campaigns and refused to commit to accepting the 2024 election results.[461][462] Analysts for The New York Times described this as an intensification of his "heads I win; tails you cheated" rhetorical strategy; the paper said the claim of a rigged election had become the backbone of the campaign.[462]

On July 13, 2024, Trump was shot in the ear in an assassination attempt at a campaign rally in Butler Township, Pennsylvania.[463][464][465] Two days later, the 2024 Republican National Convention nominated him as their presidential candidate, with Senator JD Vance as his running mate.[466] In September, he was targeted in another assassination attempt in Florida.[467]

Trump won the election in November 2024 with 312 electoral votes to incumbent vice president Kamala Harris's 226,[468] making him the second president in U.S. history after Grover Cleveland to be elected to a nonconsecutive second term.[469] He also won the popular vote with 49.8% to Harris's 48.3%.[470] His victory in 2024 was part of a global backlash against incumbent parties,[471][472] in part due to the 2021–2023 inflation surge.[473][474] Several outlets described his reelection as an extraordinary comeback.[475][476]

Second presidency (2025–present)
Main article: Second presidency of Donald Trump
For a chronological guide, see Timeline of the Donald Trump presidencies.

Trump took his second oath of office, administered by Chief Justice John G. Roberts Jr., in the Capitol rotunda, January 20, 2025.
Trump began his second term when he was inaugurated on January 20, 2025.[477] He is the oldest individual to assume the presidency,[478] and the first president with a felony conviction.[479]

Early actions, 2025–present
See also: Second presidential transition of Donald Trump and First 100 days of the second Donald Trump presidency

Trump signing executive orders at Capital One Arena on January 20, 2025
Upon taking office, Trump signed a series of executive orders, described as a "shock and awe" campaign, that tested the limits of executive authority, with many drawing immediate legal challenges.[480][481] He issued more executive orders on his first day than any other president.[482] Four days into his second term, analysis conducted by Time found that nearly two-thirds of his executive actions "mirror or partially mirror" proposals from Project 2025.[483] He pardoned around 1,500 January 6 rioters, including those who violently attacked police, and commuted the sentences of 14.[484] In his first weeks, several of his actions ignored or violated federal laws, regulations, and the Constitution.[485][486][487] In his administration's first month, Trump issued ninety executive orders, memorandums and directives,[488] and his orders and the efforts to downsize the federal government were challenged by about seventy lawsuits nationwide.[489]

Mass firings of federal employees and hiring freezes
Trump implemented a hiring freeze across the federal government, ordered telework of federal employees to be discontinued within 30 days,[490] and the at-will Schedule Policy/Career classification of employees was created.[491][492][493] He initiated mass firings of employees,[494] which many[who?] described as unprecedented or in violation of federal law,[495] with the intent of replacing them with workers more aligned with his agenda.[496] He ordered an end to diversity, equity, and inclusion (DEI) projects in the federal government and placed employees in DEI offices on leave. He rescinded Executive Order 11246, which mandated affirmative action and nondiscrimination practices for federal contractors.[497][498][499]

Trump and Musk are attempting to dismantle most of USAID.[500] On February 7, federal judge Carl Nichols delayed the placing of 2,200 employees on administrative leave pending a hearing.[501][502]

Domestic policy, 2025–present
See also: Second presidency of Donald Trump § Economy
Trump appointed oil, gas, and chemical lobbyists to the EPA to reverse climate regulations and pollution controls.[503] He declared a national energy emergency, allowing the suspension of environmental regulations, loosening the rules for fossil fuel extraction and limiting renewable energy projects.[504][505] He initiated a review of the "legality and continued applicability" of the EPA endangerment finding, which is the basis of most federal regulations on greenhouse gases,[506] and again withdrew the U.S. from the Paris Agreement on climate change.[507]

Trump frequently blamed diversity, equity, and inclusion and "wokeness" for problems in government and society, and equated diversity with incompetence.[508] He repealed and reversed pro-diversity policies in the federal government.[509][510] The administration took an aggressive approach against what it called "gender ideology", ending the ability to change the gender listed on passports, halting federal funding to entities providing gender-affirming care to individuals under 19, banning trans people from the military, and preventing trans women from competing in women's sports programs at institutions that receive federal funding.[511][512]

Immigration, 2025–present
Main articles: Immigration policy of the second Donald Trump administration and Mexico–United States border crisis § Second Trump administration (2025–present)
Further information: Deportation of illegal immigrants in the second presidency of Donald Trump and Mexico–United States border wall § Second Trump administration (2025–present)
In his first days in office, Trump instructed border patrol agents to summarily deport migrants crossing the border illegally, disabled the CBP One app that was being used to schedule border crossings, resumed the remain in Mexico policy, designated drug cartels as terrorist groups, deployed soldiers to the border, and ordered construction to be resumed on a border wall.[513][514] He indefinitely paused the refugee admissions program.[514]

Trump sought to implement mass deportations, with Immigration and Customs Enforcement (ICE) setting a goal of 1,200 to 1,500 daily arrests. However, actual numbers of arrests have lagged these goals and the rates of arrests under the Obama and Biden administrations.[515][516][517] Trump initially focused deportation operations in sanctuary cities and against individuals on "target lists" of criminals formed prior to the Trump administration. Removals were also expedited for asylum applicants who failed to meet requirements.[518][519][520] Trump also suspended refugee processing for four months and revoked the parole status of migrants who entered the U.S. under CBP One and CHNV humanitarian parole.[514][520] He attempted to remove birthright citizenship.[521] On January 29, 2025, he signed the Laken Riley Act into law.[522]

Foreign policy, 2025–present
Main article: Foreign policy of the second Donald Trump administration
Further information: Second Trump tariffs, 2025 United States trade war with Canada and Mexico, and American expansionism under Donald Trump
Trump's second term foreign policy has been described as imperialist and expansionist.[523][524] He ordered the U.S. government to stop funding and working with the WHO and announced the U.S.'s intention to formally leave the WHO.[525][526][527] He and his incoming administration helped broker a ceasefire between Israel and Hamas alongside the Biden administration, enacted a day prior to his inauguration.[528][529]

In a reversal of Biden's position on the Russian invasion of Ukraine, Reuters reported on February 19 that Trump rejected the position of Zelenskyy and called for new Ukrainian elections.[530]

Personnel, 2025–present
Main article: Second cabinet of Donald Trump
Further information: Political appointments of the second Trump administration
On February 3, 2025, the White House said that Elon Musk was a special government employee.[531] Trump gave Musk's Department of Government Efficiency (DOGE)—which is not a federal department[531]—access to many federal government agencies. Musk teams operated in eleven agencies by early February,[532] including the Treasury Department's $5 trillion payment system,[533] Small Business Administration, Office of Personnel Management, and the General Services Administration.[534]

Political practice and rhetoric
Further information: Trumpism, Political positions of Donald Trump, and Rhetoric of Donald Trump
Beginning with his 2016 campaign, Trump's politics and rhetoric led to the creation of a political movement known as Trumpism.[535] His political positions are populist,[536][537] more specifically described as right-wing populist.[538][539] He helped bring far-right fringe ideas and organizations into the mainstream.[540] Many of his actions and rhetoric have been described as authoritarian and contributing to democratic backsliding.[541][542] His political base has been compared to a cult of personality.[f]

Trump's rhetoric and actions inflame anger and exacerbate distrust through an "us" versus "them" narrative.[550] He explicitly and routinely disparages racial, religious, and ethnic minorities,[551] and scholars consistently find that racial animus regarding blacks, immigrants, and Muslims are the best predictors of support for Trump.[552] His rhetoric has been described as using fearmongering and demagogy.[553][554][page needed] The alt-right movement coalesced around and supported his candidacy, due in part to its opposition to multiculturalism and immigration.[555][556][557] He has a strong appeal to evangelical Christian voters and Christian nationalists,[558] and his rallies take on the symbols, rhetoric and agenda of Christian nationalism.[559]

Racial and gender views
Many of Trump's comments and actions have been described as racist.[560] In national polling, about half of respondents said that he is racist; a greater proportion believed that he emboldened racists.[561] Several studies and surveys found that racist attitudes fueled his political ascent and were more important than economic factors in determining the allegiance of Trump voters.[562] Racist and Islamophobic attitudes are a powerful indicator of support for Trump.[563] He has also been accused of racism for insisting a group of five black and Latino teenagers were guilty of raping a white woman in the 1989 Central Park jogger case, even after they were exonerated in 2002 when the actual rapist confessed and his DNA matched the evidence. In 2024, the men sued Trump for defamation after he said in a televised debate that they had committed the crime and killed the woman.[564]

Trump answering questions about the Unite the Right rally in Charlottesville
In 2011, when he was reportedly considering a presidential run, Trump became the leading proponent of the racist "birther" conspiracy theory, alleging that Barack Obama, the first black U.S. president, was not born in the United States.[565] In April, he claimed credit for pressuring the White House to publish the "long-form" birth certificate, which he considered fraudulent, and later said this made him "very popular".[566] In September 2016, amid pressure, he acknowledged that Obama was born in the U.S.[567] In 2017, he reportedly expressed birther views privately.[568] During the 2024 presidential campaign, he made false attacks against the racial identity of his opponent, Kamala Harris, that were described as reminiscent of the birther conspiracy theory.[569]

Trump has a history of belittling women when speaking to the media and on social media.[570][571] He made lewd comments, disparaged women's physical appearances, and referred to them using derogatory epithets.[571] At least 25 women publicly accused him of sexual misconduct, including rape, kissing without consent, groping, looking under women's skirts, and walking in on naked teenage pageant contestants. He has denied the allegations.[572] In October 2016, a 2005 "hot mic" recording surfaced in which he bragged about kissing and groping women without their consent, saying that, "when you're a star, they let you do it. You can do anything. ... Grab 'em by the pussy."[573] He characterized the comments as "locker-room talk".[574][575] The incident's widespread media exposure led to his first public apology, videotaped during his 2016 presidential campaign.[576]

Link to violence and hate crimes
Further information: Rhetoric of Donald Trump § Violence and dehumanization

Trump's refusal to condemn the white supremacist Proud Boys during a 2020 presidential debate[577] and his comment, "Proud Boys, stand back and stand by", were attributed to increased recruitment for the pro-Trump group.[578]
Trump has been identified as a key figure in increasing political violence in America, both for and against him.[579][580][581] He is described as embracing extremism, conspiracy theories such as Q-Anon, and far-right militia movements to a greater extent than any modern American president,[582][583] and engaging in stochastic terrorism.[584][585]

Research suggests Trump's rhetoric is associated with an increased incidence of hate crimes,[586][587] and that he has an emboldening effect on expressing prejudicial attitudes due to his normalization of explicit racial rhetoric.[588] During his 2016 campaign, he urged or praised physical attacks against protesters or reporters.[589][590] Numerous defendants investigated or prosecuted for violent acts and hate crimes, including participants in the storming of the U.S. Capitol, cited his rhetoric in arguing that they were not culpable or should receive leniency.[591][592] A nationwide review by ABC News in May 2020 identified at least 54 criminal cases, from August 2015 to April 2020, in which he was invoked in direct connection with violence or threats of violence mostly by white men and primarily against minorities.[593] Trump's normalization and revisionist history of the January 6 Capitol attack, and grant of clemency to all January 6 rioters, were described by counterterrorism researchers as encouraging future political violence.[594][595]

Conspiracy theories
Main article: List of conspiracy theories promoted by Donald Trump
Before and throughout his presidency, Trump promoted numerous conspiracy theories, including Obama birtherism, global warming being a hoax, and alleged Ukrainian interference in U.S. elections.[596][597][598] During and since the 2020 presidential election, he promoted various conspiracy theories for his defeat that were characterized as "the big lie".[599][600]

Truthfulness
Main article: False or misleading statements by Donald Trump
Chart depicting false or misleading claims made by Trump
Fact-checkers from The Washington Post,[601] the Toronto Star,[602] and CNN[603] compiled data on "false or misleading claims" (orange background), and "false claims" (violet foreground), respectively.
As a candidate and as president, Trump frequently makes false statements in public remarks[604][114] to an extent unprecedented in American politics.[604][605][606] His falsehoods are a distinctive part of his political identity[605] and have been described as firehosing.[607] His false and misleading statements were documented by fact-checkers, including at The Washington Post, which tallied 30,573 false or misleading statements made by him during his first presidency,[601] increasing in frequency over time.[608]

Some of Trump's falsehoods were inconsequential, such as his repeated claim of the "biggest inaugural crowd ever".[609][610] Others had more far-reaching effects, such as his promotion of antimalarial drugs as an unproven treatment for COVID-19,[611][612] causing a U.S. shortage of these drugs and panic-buying in Africa and South Asia.[613][614] Other misinformation, such as misattributing a rise in crime in England and Wales to the "spread of radical Islamic terror", served his domestic political purposes.[615] His attacks on mail-in ballots and other election practices weakened public faith in the integrity of the 2020 presidential election,[616][617] while his disinformation about the pandemic delayed and weakened the national response to it.[618][619][620] He habitually does not apologize for his falsehoods.[621] Until 2018, the media rarely referred to his falsehoods as lies, including when he repeated demonstrably false statements.[622][623][624]

Social media
Main article: Social media use by Donald Trump
Trump's social media presence attracted worldwide attention after he joined Twitter in 2009. He tweeted frequently during his 2016 campaign and as president until Twitter banned him after the January 6 attack.[625] He often used Twitter to communicate directly with the public and sideline the press.[626] In June 2017, the White House press secretary said that his tweets were official presidential statements.[627]

After years of criticism for allowing Trump to post misinformation and falsehoods, Twitter began to tag some of his tweets with fact-checks in May 2020.[628] In response, he tweeted that social media platforms "totally silence" conservatives and that he would "strongly regulate, or close them down".[629] In the days after the storming of the Capitol, he was banned from Facebook, Instagram, Twitter and other platforms.[630] The loss of his social media presence diminished his ability to shape events[631][632] and prompted a dramatic decrease in the volume of misinformation shared on Twitter.[633] In February 2022, he launched social media platform Truth Social where he only attracted a fraction of his Twitter following.[634] Elon Musk, after acquiring Twitter, reinstated his Twitter account in November 2022.[635][636] Meta Platforms' two-year ban lapsed in January 2023, allowing him to return to Facebook and Instagram,[637] although in 2024, he continued to call the company an "enemy of the people".[638] In January 2025, Meta agreed to pay $25 million to settle a 2021 lawsuit filed by Trump over his suspension.[639]

Relationship with the press
Further information: First presidency of Donald Trump § Relationship with the news media, and Personal and business legal affairs of Donald Trump
Trump, seated at the Resolute Desk in the White House, speaking to a crowd of reporters with boom microphones in front of him and public officials behind him
Trump talking to the press, March 2017
Trump sought media attention throughout his career, sustaining a "love-hate" relationship with the press.[640] In the 2016 campaign, he benefited from a record amount of free media coverage.[641] The New York Times writer Amy Chozick wrote in 2018 that his media dominance enthralled the public and created "must-see TV".[642] As a candidate and as president, he frequently accused the press of bias, calling it the "fake news media" and "the enemy of the people".[643] In 2018, journalist Lesley Stahl said that he had privately told her that he intentionally discredited the media "so when you write negative stories about me no one will believe you".[644]

The first Trump presidency reduced formal press briefings from about a hundred in 2017 to about half that in 2018 and to two in 2019; they also revoked the press passes of two White House reporters, which were restored by the courts.[645] Trump's 2020 presidential campaign sued The New York Times, The Washington Post, and CNN for defamation in opinion pieces about his stance on Russian election interference. All the suits were dismissed. The Atlantic characterized the suits as an intimidation tactic.[646][647] By 2024, he repeatedly voiced support for outlawing political dissent and criticism,[648] and said that reporters should be prosecuted for not divulging confidential sources and media companies should possibly lose their broadcast licenses for unfavorable coverage of him.[649] In 2024, he sued ABC News for defamation after George Stephanopoulos said on-air that a jury had found him civilly liable for raping E. Jean Carroll. The case was settled in December with ABC's parent company, Walt Disney, apologizing for the inaccurate claims about Trump and agreeing to donate $15 million to his future presidential library.[650][651][652]

Personal life
Family
Further information: Family of Donald Trump
In 1977, Trump married Czech model Ivana Zelníčková.[653] They had three children: Donald Jr. (b. 1977), Ivanka (b. 1981), and Eric (b. 1984). The couple divorced in 1990, following his affair with model and actress Marla Maples.[654] He and Maples married in 1993 and divorced in 1999. They have one daughter, Tiffany (b. 1993), whom Maples raised in California.[655] In 2005, he married Slovenian model Melania Knauss.[656] They have one son, Barron (b. 2006).[657]

Health
Main article: Age and health concerns about Donald Trump
Trump says he has never drunk alcohol, smoked cigarettes, or used drugs.[658][659] He sleeps about four or five hours a night.[660][661] He has called golfing his "primary form of exercise", but usually does not walk the course.[662] He considers exercise a waste of energy because he believes the body is "like a battery, with a finite amount of energy", which is depleted by exercise.[663][664] In 2015, his campaign released a letter from his longtime personal physician, Harold Bornstein, stating that he would "be the healthiest individual ever elected to the presidency".[665] In 2018, Bornstein said Trump had dictated the contents of the letter and that three of Trump's agents had seized his medical records in a February 2017 raid on Bornstein's office.[665][666]

Religion
Main article: Donald Trump and religion
Trump declared that he was a Presbyterian and a Protestant in 2016,[667][668] though in 2020, he began to identify as a nondenominational Christian.[669]

Assessments
Public image
Main articles: Public image of Donald Trump and Donald Trump in popular culture
See also: Opinion polling on the first Donald Trump administration and Opinion polling on the second Donald Trump administration
A Gallup poll in 134 countries comparing the approval ratings of U.S. leadership between 2016 and 2017 found that Trump led Obama in job approval in 29 countries, most of them non-democracies;[670] approval of U.S. leadership plummeted among allies and G7 countries.[671] By mid-2020, 16 percent of international respondents to a 13-nation Pew Research poll expressed confidence in him, lower than China's Xi Jinping and Russia's Vladimir Putin.[672]

During his first presidency, research from 2020 found that Trump had a stronger impact on popular assessments towards American political parties and partisan opinions than any president since the Truman administration.[673] In 2021, he was identified as the only president never to reach a 50 percent approval rating in the Gallup poll, which dates to 1938, partially due to a record-high partisan gap in his approval ratings: 88 percent among Republicans and 7 percent among Democrats.[674] His early ratings were unusually stable, ranging between 35 and 49 percent.[675] He finished his term with a rating between 29 and 34 percent—the lowest of any president since modern polling began—and a record-low average of 41 percent throughout his presidency.[674][676]

In Gallup's annual poll asking Americans to name the man they admire the most, Trump placed second to Obama in 2017 and 2018, tied with Obama for first in 2019, and placed first in 2020.[677][678] Since Gallup started conducting the poll in 1946, he was the first elected president not to be named most admired in his first year in office.[679]

According to Gallup, Trump began his second term with an approval rating of 47% and a disapproval rating of 48%. His approval rating was extremely politically polarized, being approved by 91% of Republicans, 46% of independents, and 6% of Democrats.[680]

Scholarly rankings
Further information: Historical rankings of presidents of the United States
In C-SPAN's "Presidential Historians Survey 2021",[681] historians ranked Trump as the fourth-worst president. He rated lowest in the leadership characteristics categories for moral authority and administrative skills.[682][683] The Siena College Research Institute's 2022 survey ranked him 43rd out of 45 presidents. He was ranked near the bottom in all categories except for luck, willingness to take risks, and party leadership, and he ranked last in several categories.[684] In 2018 and 2024, surveys of members of the American Political Science Association ranked him the worst president.[685][686]"""

from bpe.regex import Regex
from bpe.utils import bytepair_encoding, find_max_occuring_pair, find_pairs, replace_pair

regex = Regex()

regex_text = regex.match_pattern(text, "gpt4")

vocab = {idx: bytes([idx]) for idx in range(256)}
idx = 256
vocab_size = 260

# encode
tokens = [list(t.encode("utf-8")) for t in regex_text]

merge_dict = {}
while idx <= vocab_size:
    pairs = {}
    for token in tokens:
        find_pairs(token, pairs)

    # find max pair
    token_pair = find_max_occuring_pair(pairs)

    if not token_pair:  # if no pair occurs
        print("No more pairs to merge")
        break
    merge_dict[token_pair] = idx
    vocab[idx] = vocab[token_pair[0]] + vocab[token_pair[1]]
    print(f"Token Pair: {token_pair}")
    tokens = [replace_pair(token, token_pair, idx) for token in tokens]
    idx += 1

# print(tokens)
print(merge_dict)
print(vocab)
